version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  notification:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    command: ["/bin/sh", "-c", "while true; do sleep 1; done"]

volumes:
  data:
    driver: local